# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('schoolCreator', '0004_schoolusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolusers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_creator',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='login.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SchoolUsers',
        ),
    ]
