# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolCreator', '0005_auto_20170125_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_creator',
        ),
    ]
