# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolCreator', '0007_comments_comment_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.TextField(default='Someone', max_length=100),
            preserve_default=False,
        ),
    ]
